name: simulation
root: ./
startup_window: status
pre_window: export USV_NAME=wamv;
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch offshore_uav_pack offshore_rig.launch
  - spawn_wamv:
      layout: tiled
      panes:
        - history -s roslaunch offshore_uav_pack wamv.launch
  - controlWAMV:
      layout: tiled
      panes:
        - history -s roslaunch offshore_uav_pack controlWAMV.launch
  - RQT_Publisher:
      layout: tiled
      panes:
        - history -s rosrun rqt_publisher rqt_publisher